export const PageSize = 4;

export const Data = [
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Enterprise management systems' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'Enterprise management systems' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Customer-enabling services' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Enterprise management systems' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'Customer-enabling services' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'Enterprise management systems' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'Enterprise management systems' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'Enterprise management systems' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'ECommerce & Retail Software development' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'Enterprise management systems' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'Customer-enabling services' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'ECommerce & Retail Software development' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'New business ideas' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Enterprise management systems' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'Enterprise management systems' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Customer-enabling services' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Enterprise management systems' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'Customer-enabling services' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'Enterprise management systems' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'Enterprise management systems' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'Enterprise management systems' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'ECommerce & Retail Software development' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'Enterprise management systems' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'New business ideas' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'Customer-enabling services' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'ECommerce & Retail Software development' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration3.svg', category: 'New business ideas' },
  { title: 'Marcos-StarcatXR', content: 'Website', img: '/illustration1.webp', category: 'Customer-enabling services' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'ECommerce & Retail Software development' },
  { title: 'Nistone-Loan', content: 'Phone Application', img: '/illustration2.svg', category: 'Others' },
]

export const ListSelect = [
  { id: 1, title: 'Enterprise management systems' },
  { id: 2, title: 'ECommerce & Retail Software development' },
  { id: 3, title: 'Customer-enabling services' },
  { id: 4, title: 'New business ideas' },
  { id: 5, title: 'Others' },
]
